name: 'action-html-to-image'
description: 'Renders images from HTML'
author: 'Sentry'
inputs:
  base-path:
    description: 'base path to snapshots'
  css-path:
    description: 'path to custom css to inject'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/getsentry/action-html-to-image:latest'
